### Source Plugins below "${ZSH_PLUGINS_ENABLED}/"
export ZDOTDIR="${HOME}/.config/zsh"
export ZSH_PLUGINS_AVAIL="${ZDOTDIR}/new-zsh-config/zsh/user/plugins/plugins-available"
export ZSH_PLUGINS_ENABLED="${ZDOTDIR}/new-zsh-config/zsh/user/plugins/plugins-enabled"

#
# ln -s -r "${ZSH_PLUGINS_AVAIL}/copier" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-colored-man-pages" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-autosuggestions" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/autoenv" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-autoswitch-virtualenv" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/forgit" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/undollar" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/expand-ealias.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/tsm" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/k" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/z.lua" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/cheatsheet" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-autopair" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/history-search-multi-word/" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-change-case" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/symmetric-ctrl-z" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-system-clipboard" "${ZSH_PLUGINS_ENABLED}/"
# ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-sudo" "${ZSH_PLUGINS_ENABLED}/"
#

ln -s -r "${ZSH_PLUGINS_AVAIL}/copier/copier.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-colored-man-pages/colored-man-pages.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/autoenv/autoenv.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-autoswitch-virtualenv/zsh-autoswitch-virtualenv.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/forgit/forgit.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/undollar/undollar.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/expand-ealias.plugin.zsh/expand-ealias.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/tsm/tsm.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/k/k.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/z.lua/z.lua.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/cheatsheet/cheatsheet.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-autopair/autopair.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/history-search-multi-word/history-search-multi-word.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-change-case/change-case.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/symmetric-ctrl-z/symmetric-ctrl-z.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-system-clipboard/zsh-system-clipboard.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
ln -s -r "${ZSH_PLUGINS_AVAIL}/zsh-sudo/sudo.plugin.zsh" "${ZSH_PLUGINS_ENABLED}/"
