gui:
    authorColors: {}
    branchColors: {}
    scrollHeight: 2
    scrollPastBottom: true
    mouseEvents: true
    skipDiscardChangeWarning: false
    skipStashWarning: false
    sidePanelWidth: 0.3333
    expandFocusedSidePanel: true
    mainPanelSplitMode: flexible
    language: auto
    theme:
        lightTheme: false
        activeBorderColor:
            - magenta
            - bold
        inactiveBorderColor:
            - blue
        optionsTextColor:
            - cyan
        selectedLineColor:
            - magenta
            - bold
        selectedLineBgColor:
            - black
        selectedRangeBgColor:
            - blue
        cherryPickedCommitBgColor:
            - blue
        cherryPickedCommitFgColor:
            - cyan
        unstagedChangesColor:
            - red
            - bold
    commitLength:
        show: true
    skipNoStagedFilesWarning: false
    showListFooter: true
    showFileTree: true
    showRandomTip: true
    showCommandLog: true
    commandLogSize: 100
git:
    paging:
        colorArg: always
        pager: ""
        useConfig: true
    commit:
        signOff: false
    merging:
        manualCommit: false
        args: ""
    skipHookPrefix: WIP
    autoFetch: true
    branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
    allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
    overrideGpg: false
    disableForcePushing: false
    commitPrefixes: {}
    parseEmoji: true
    log:
        order: topo-order
        showGraph: when-maximised
    diffContextSize: 5
update:
    method: prompt
    days: 14
refresher:
    refreshInterval: 10
    fetchInterval: 60
reporting: undetermined
splashUpdatesIndex: 0
confirmOnQuit: true
quitOnTopLevelReturn: false
keybinding:
    universal:
        quit: q
        quit-alt1: Z
        return: <esc>
        quitWithoutChangingDirectory: Q
        togglePanel: <tab>
        prevItem: <up>
        nextItem: <down>
        prevItem-alt: k
        nextItem-alt: j
        prevPage: ','
        nextPage: .
        scrollLeft: H
        scrollRight: L
        gotoTop: <
        gotoBottom: '>'
        prevBlock: <left>
        nextBlock: <right>
        prevBlock-alt: h
        nextBlock-alt: l
        nextBlock-alt2: <tab>
        prevBlock-alt2: <backtab>
        jumpToBlock:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
        nextMatch: "n"
        prevMatch: "N"
        startSearch: /
        optionMenu: x
        optionMenu-alt1: '?'
        select: <space>
        goInto: <enter>
        confirm: <enter>
        confirm-alt1: "y"
        remove: d
        new: "n"
        edit: e
        openFile: o
        scrollUpMain: <pgup>
        scrollDownMain: <pgdown>
        scrollUpMain-alt1: K
        scrollDownMain-alt1: J
        scrollUpMain-alt2: <c-u>
        scrollDownMain-alt2: <c-d>
        executeCustomCommand: ':'
        createRebaseOptionsMenu: m
        pushFiles: P
        pullFiles: p
        refresh: R
        createPatchOptionsMenu: <c-p>
        nextTab: ']'
        prevTab: '['
        nextScreenMode: +
        prevScreenMode: _
        undo: z
        redo: <c-z>
        filteringMenu: <c-s>
        diffingMenu: W
        diffingMenu-alt: <c-e>
        copyToClipboard: <c-c>
        openRecentRepos: <c-r>
        submitEditorText: <enter>
        appendNewline: <a-enter>
        extrasMenu: '@'
        toggleWhitespaceInDiffView: <c-w>
        increaseContextInDiffView: '}'
        decreaseContextInDiffView: '{'
    status:
        checkForUpdate: u
        recentRepos: <enter>
        allBranchesLogGraph: a
    files:
        commitChanges: c
        commitChangesWithoutHook: w
        amendLastCommit: A
        commitChangesWithEditor: C
        ignoreFile: i
        refreshFiles: r
        stashAllChanges: s
        viewStashOptions: S
        toggleStagedAll: a
        viewResetOptions: D
        fetch: f
        toggleTreeView: '`'
        openMergeTool: M
        openStatusFilter: <c-b>
    branches:
        createPullRequest: o
        viewPullRequestOptions: O
        copyPullRequestURL: <c-y>
        checkoutBranchByName: c
        forceCheckoutBranch: F
        rebaseBranch: r
        renameBranch: R
        mergeIntoCurrentBranch: M
        viewGitFlowOptions: i
        fastForward: f
        pushTag: P
        setUpstream: u
        fetchRemote: f
    commits:
        squashDown: s
        renameCommit: r
        renameCommitWithEditor: R
        viewResetOptions: g
        markCommitAsFixup: f
        createFixupCommit: F
        squashAboveCommits: S
        moveDownCommit: <c-j>
        moveUpCommit: <c-k>
        amendToCommit: A
        pickCommit: p
        revertCommit: t
        cherryPickCopy: c
        cherryPickCopyRange: C
        pasteCommits: v
        tagCommit: T
        checkoutCommit: <space>
        resetCherryPick: <c-R>
        copyCommitMessageToClipboard: <c-y>
        openLogMenu: <c-l>
        openInBrowser: o
        viewBisectOptions: b
    stash:
        popStash: g
    commitFiles:
        checkoutCommitFile: c
    main:
        toggleDragSelect: v
        toggleDragSelect-alt: V
        toggleSelectHunk: a
        pickBothHunks: b
    submodules:
        init: i
        update: u
        bulkMenu: b
os:
    editCommandTemplate: '{{editor}} {{filename}}'
    openCommand: xdg-open {{filename}} >/dev/null
    openLinkCommand: xdg-open {{link}} >/dev/null
disableStartupPopups: false
customCommands: []
services: {}
notARepository: prompt
promptToReturnFromSubprocess: true
