[colors]
foreground = "#3760bf"
background = "#e1e2e7"
cursor_bg = "#3760bf"
cursor_border = "#3760bf"
cursor_fg = "#e1e2e7"
selection_bg = "#899bf8"
selection_fg = "#3760bf"

ansi = ["#e9e9ed", "#fb005f", "#267836", "#6c6d0c", "#2d7fe5", "#9e29af", "#005c5c", "#727eaf"]
brights = ["#cdd0e7", "#fb005f", "#267836", "#6c6d0c", "#2d7fe5", "#9e29af", "#005c5c", "#3760bf"]
  