[colors]
foreground = "#c0caf5"
background = "#1a1b26"
cursor_bg = "#c0caf5"
cursor_border = "#c0caf5"
cursor_fg = "#1a1b26"
selection_bg = "#1A46B4"
selection_fg = "#c0caf5"

ansi = ["#15161E", "#ff7690", "#4edf6a", "#c9cb20", "#75a2f7", "#da50f0", "#7dffff", "#98a0c5"]
brights = ["#202646", "#ff7690", "#4edf6a", "#c9cb20", "#75a2f7", "#da50f0", "#7dffff", "#c0caf5"]
  