name: shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Shellcheck .zshrc
        run: zsh -c "shellcheck --color=always --exclude=1072,1073,1009,2148 --check-sourced .config/zsh/.zshrc .config/zsh/zsh/user/zsh.d/*.zsh .config/zsh/zsh/user/plugins-enabled/*.zsh"
