name: Check Zsh Configuration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-zsh-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up ZSH docker container
        run: docker run --rm -i -v $(pwd):/root -w /root zshusers/zsh zsh --interactive #.config/zsh/.zshrc
